title: WOD's UP
author: Robert Da Silva
email: webmaster@robdasilva.com
description: >
  Daily workouts you can definitely do anywhere

google_analytics: UA-161521615-1
instagram_username: wodsup.today
mailchimp:
  audience: c44b568c59
  user: 50d586277dfeb14b7cd919e92

future: true
timezone: UTC

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
