title: WOD's UP
author: Robert Schweizer
email: mail@robertschweizer.me
description: >
  Daily workouts for individual athletes, teams and classes.

google_analytics: UA-161521615-1
instagram_username: wodsup.today

collections:
  - warmup-games

main_navigation:
  - warmup-games

future: true
timezone: UTC

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
