title: WOD's UP
author: Robert Schweizer
email: mail@robertschweizer.me
description: >
  Daily workouts you can definitely do anywhere

google_analytics: UA-161521615-1
instagram_username: wodsup.today

future: true
timezone: UTC

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
